apiVersion: v1
kind: Service
metadata:
  name: test-svc-4
  namespace: test-svc-4  # Specify the namespace
spec:
  selector:
    app: test-svc-4  # Match pods with the label app=test-svc-4
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 8080  # Port on the container
  type: ClusterIP  # Default service type (accessible only within the cluster)
